import type { Config } from "tailwindcss"

const config = {
  // Uses the content paths generated by create-next-app and shadcn/ui
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      // Custom Colors Redefined to Match HTML
      colors: {
        'primary': {
          DEFAULT: '#171716', // Maverick-base (Dark Text/Background)
          foreground: '#FAFAFA', // White/Light contrast text on primary
        },
        'secondary': {
          DEFAULT: '#5AD5E2', // Primary Blue/Cyan (Target color for button/hover text)
          foreground: '#171716', // Dark text on secondary
        },
        'tertiary': {
          DEFAULT: '#A9D834', // Primary Green/Lime (Maverick-Accent)
          foreground: '#171716', // Dark text on tertiary
        },
        'form-gold': '#FFC33A', // Used for main CTA button
        'header-dark': '#1a1919', // Header background
        'footer-dark': '#121111', // Footer background

        // --- NEW WHATSAPP GREEN ---
        'whatsapp-green': '#25D366', 

        // Standard shadcn/ui colors (Consolidated)
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      // --- Custom Shake Animation Definition ---
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "shake-logo": { // Custom Keyframe Added
            "0%": { transform: "translateX(0)" },
            "25%": { transform: "translateX(-3px) rotate(-2deg)" },
            "50%": { transform: "translateX(3px) rotate(2deg)" },
            "75%": { transform: "translateX(-3px) rotate(-2deg)" },
            "100%": { transform: "translateX(0)" },
        }
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "shake": "shake-logo 1.5s ease-in-out 3", // Custom Animation Class
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config